version: "3.9"

services:
  # db:
  #   image: postgres:14.4-bullseye
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  web:
    build: .
    volumes:
      - .:/code
      - staticfiles:/code/staticfiles
    ports:
      - "8000:8000"
    # environment:
    #   - POSTGRES_NAME=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    # depends_on:
    #   - db
  server:
    image: nginx:1.23
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/home/composeexample/staticfiles
    ports:
      - "80:80"
    depends_on:
      - "web"
volumes:
  staticfiles: